#!/usr/bin/env bash
# Summary: phpenv composer plugin

set -e

prefix=$(phpenv prefix)

if [ -z "$prefix" ]; then
  echo "cannot get phpenv prefix" 1>&2
  exit 1
fi

php_bin=$prefix/bin/php
composer_home=$prefix/composer
composer_phar=$prefix/composer/composer.phar

if [ ! -f "$composer_phar" ]; then
  echo "Download composer.phar ..." 1>&2

  if [ ! -d "$composer_home" ]; then
    mkdir -p "$composer_home"
  fi

  tmp="$(dirname "$(mktemp --dry-run 2>/dev/null)")"
  tmp=${tmp:-/tmp}

  curl -sS https://getcomposer.org/installer | "$php_bin" -- --install-dir="$tmp"

  if [ $? -eq 0 ]; then
    echo "Move composer.phar to $composer_home" 1>&2
    mv "$tmp/composer.phar" "$composer_home/composer.phar"
  fi
fi

if [ ! -f "$composer_phar" ]; then
  echo "composer.phar notfount" 1>&2
  exit 1
fi

export COMPOSER_CACHE_DIR=$("$php_bin" "$composer_phar" config -g cache-dir)
export COMPOSER_HOME=$composer_home

"$php_bin" "$composer_phar" "$@"
